namespace FirstProject.Encounters
{
    public enum Background
    {
        FOREST,
        FIELD,
        ASTRAL_PLANE,
        CAVE,
        CITY_SQUARE_1,
        CITY_SQUARE_2,
        CITY_SQUARE_3,
        CITY_SQUARE_NIGHT,
        CITY_SQUARE_NIGHT_2,
        DESERT,
        DESERT_HOLES,
        DUNGEON,
        FIELD_SUNRISE,
        FOREST_NIGHT,
        GHOST_SHIP,
        HILL,
        INSIDE_TREE,
        LAKE,
        LIBRARY,
        LIBRARY_2,
        SHIP,
        STONE_HOUSE,
        TOMB,
        TOWER,
        TOWER_SUNRISE,
    }
}
